# Generated by Django 6.0.2 on 2026-02-18 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('grade', models.CharField(max_length=32)),
                ('grade_type', models.CharField(blank=True, max_length=32)),
                ('grade_subtype', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academic_management.academicyear')),
                ('students', models.ManyToManyField(blank=True, related_name='student_grades', through='academic_management.StudentEnrollment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-academic_year', 'name'],
                'indexes': [models.Index(fields=['academic_year', 'grade'], name='grade_manag_academi_b8beab_idx'), models.Index(fields=['grade', 'grade_type', 'grade_subtype'], name='grade_manag_grade_93061e_idx')],
                'unique_together': {('name', 'grade', 'academic_year', 'grade_type', 'grade_subtype')},
            },
        ),
    ]
