# Generated by Django 6.0.2 on 2026-02-18 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_date_modified_user_deleted_at_user_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolUser',
            fields=[
            ],
            options={
                'verbose_name': 'School User',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('address', models.TextField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, help_text='Additional attributes for the profile (stored as JSON)', null=True)),
                ('user', models.OneToOneField(help_text='One-to-one relationship ensures each user has only one profile of this type', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='user_management.schooluser')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='SchoolStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('address', models.TextField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, help_text='Additional attributes for the profile (stored as JSON)', null=True)),
                ('user', models.OneToOneField(help_text='One-to-one relationship ensures each user has only one profile of this type', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='user_management.schooluser')),
            ],
            options={
                'verbose_name': 'School Staff',
                'verbose_name_plural': 'School Staff',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('address', models.TextField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, help_text='Additional attributes for the profile (stored as JSON)', null=True)),
                ('children', models.ManyToManyField(blank=True, help_text='Students associated with this parent', related_name='parents', to='user_management.schooluser')),
                ('user', models.OneToOneField(help_text='One-to-one relationship ensures each user has only one profile of this type', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='user_management.schooluser')),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
            },
        ),
    ]
