# Generated by Django 6.0.2 on 2026-04-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(blank=True, help_text='Students associated with this parent', related_name='parent_profiles', to='user_management.schooluser'),
        ),
    ]
