# Generated by Django 6.0.2 on 2026-04-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffmember',
            new_name='staff_manag_departm_ebb757_idx',
            old_name='staff_manag_departm_577364_idx',
        ),
        migrations.RenameIndex(
            model_name='staffmember',
            new_name='staff_manag_is_acti_ff8932_idx',
            old_name='staff_manag_is_acti_75af0f_idx',
        ),
        migrations.RenameIndex(
            model_name='teacher',
            new_name='staff_manag_departm_5352c6_idx',
            old_name='staff_manag_departm_0f3fdd_idx',
        ),
        migrations.RenameIndex(
            model_name='teacher',
            new_name='staff_manag_is_acti_8cf6bf_idx',
            old_name='staff_manag_is_acti_f1ad01_idx',
        ),
    ]
