# Generated by Django 6.0.2 on 2026-02-18 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYearSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('current_step', models.CharField(choices=[('BASIC_INFO', 'Basic Information'), ('IMPORT_GRADES', 'Import Grades'), ('IMPORT_STUDENTS', 'Import Students'), ('ASSIGN_CLASSROOMS', 'Assign Classrooms'), ('REVIEW', 'Review and Confirm'), ('COMPLETED', 'Setup Completed')], default='BASIC_INFO', max_length=20)),
                ('basic_info_completed', models.BooleanField(default=False)),
                ('import_grades_completed', models.BooleanField(default=False)),
                ('import_students_completed', models.BooleanField(default=False)),
                ('assign_classrooms_completed', models.BooleanField(default=False)),
                ('review_completed', models.BooleanField(default=False)),
                ('grades_import_method', models.CharField(choices=[('NONE', 'Not Imported'), ('MANUAL', 'Manual Entry'), ('CSV', 'CSV File Upload'), ('API', 'API Integration')], default='NONE', max_length=10)),
                ('students_import_method', models.CharField(choices=[('NONE', 'Not Imported'), ('MANUAL', 'Manual Entry'), ('CSV', 'CSV File Upload'), ('API', 'API Integration')], default='NONE', max_length=10)),
                ('classrooms_import_method', models.CharField(choices=[('NONE', 'Not Imported'), ('MANUAL', 'Manual Entry'), ('CSV', 'CSV File Upload'), ('API', 'API Integration')], default='NONE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_progress', to='academic_management.academicyear')),
            ],
            options={
                'ordering': ['-date_joined', '-date_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('task_type', models.CharField(choices=[('GRADES', 'Grades'), ('STUDENTS', 'Students'), ('CLASSROOMS', 'Classrooms')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('file_path', models.CharField(blank=True, help_text='Path to import file if applicable', max_length=255, null=True)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, help_text='Details of errors encountered during import', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_tasks', to='academic_management.academicyear')),
            ],
            options={
                'ordering': ['-date_joined', '-date_modified'],
                'abstract': False,
            },
        ),
    ]
