# Generated by Django 6.0.2 on 2026-02-18 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('SETUP', 'Setup Phase'), ('ENROLLMENT', 'Enrollment Phase'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='SETUP', help_text='Current status of the academic year', max_length=20)),
                ('deployment_type', models.CharField(choices=[('FRESH_START', 'Fresh Start (New Academic Year)'), ('MID_YEAR', 'Mid-Year Adoption')], default='FRESH_START', help_text='Whether this is a fresh academic year or mid-year adoption', max_length=20)),
                ('setup_completed', models.BooleanField(default=False, help_text='Whether the initial setup process has been completed')),
                ('enrollment_start_date', models.DateField(blank=True, help_text='Start date for enrollment period (optional for mid-year adoption)', null=True)),
                ('enrollment_end_date', models.DateField(blank=True, help_text='End date for enrollment period (optional for mid-year adoption)', null=True)),
            ],
            options={
                'ordering': ['-date_joined', '-date_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_management.academicyear')),
            ],
            options={
                'verbose_name': 'Grade Student',
                'verbose_name_plural': 'Grade Students',
            },
        ),
    ]
