# Generated by Django 6.0.2 on 2026-04-22 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_management', '0002_initial'),
        ('grade_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'base_manager_name': 'objects', 'verbose_name': 'Grade Student', 'verbose_name_plural': 'Grade Students'},
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student', 'academic_year'), name='unique_student_per_year_not_deleted'),
        ),
    ]
